@startuml
'https://plantuml.com/class-diagram

package Combinatorics  #DDDDDD
{
!include BFS.iuml
!include Graph.iuml
}

package LabyrinthGame
{
package IO #DDDDDD
{
!include IO.iuml
}

package Geo
{
!include geo.iuml
}

!include game.iuml

}
@enduml